/*izbrisano je let assert = chai.assert; da bi mogli zajedno da se pokrecu testovi */
describe('TestoviParser', function() {
 describe('porediRezultate()', function() {
   it('Identicni testovi, greske samo iz rez2 TEST 1', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":0,\"pending\":0,\"failures\":5,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}");
     assert.equal(rezultat.promjena, "0%");
     assert.equal(rezultat.greske.length, 5);
   });
   it('Identicni testovi, greske samo iz rez2 TEST 2', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":3,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "60%");
     assert.equal(rezultat.greske.length, 2);
   });
   it('Identicni testovi, greske samo iz rez2 TEST 3', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":4,\"passes\":2,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":4,\"passes\":3,\"pending\":0,\"failures\":1,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "75%");
     assert.equal(rezultat.greske.length, 1);
   });
   it('Identicni testovi, greske samo iz rez2 TEST 4', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":4,\"passes\":2,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":4,\"passes\":0,\"pending\":0,\"failures\":4,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test2\",\"fullTitle\":\"ergerg\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test1\",\"fullTitle\":\"wefwef\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"qweqf\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"rtjn\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}");
     assert.equal(rezultat.promjena, "0%");
     assert.equal(rezultat.greske.length, 4);
     assert.equal(rezultat.greske[0], "ergerg");
     assert.equal(rezultat.greske[1], "qweqf");
     assert.equal(rezultat.greske[2], "rtjn");
     assert.equal(rezultat.greske[3], "wefwef");
   });
   it('Razliciti testovi TEST 1', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test8\",\"fullTitle\":\"Test8\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test9\",\"fullTitle\":\"Test9\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test10\",\"fullTitle\":\"Test10\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test8\",\"fullTitle\":\"Test8\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test9\",\"fullTitle\":\"Test9\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test10\",\"fullTitle\":\"Test10\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "75%");
     assert.equal(rezultat.greske.length, 6);
   });
   it('Razliciti testovi TEST 2', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "71.43%");
     assert.equal(rezultat.greske.length, 4);
     assert.equal(rezultat.greske[0], "Test4");
     assert.equal(rezultat.greske[1], "Test5");
     assert.equal(rezultat.greske[2], "Test6");
     assert.equal(rezultat.greske[3], "Test7");
   });
   it('Razliciti testovi TEST 3', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test6\",\"fullTitle\":\"Test6\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test7\",\"fullTitle\":\"Test7\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "71.43%");
     assert.equal(rezultat.greske.length, 4);
     assert.equal(rezultat.greske[0], "Test4");
     assert.equal(rezultat.greske[1], "Test5");
     assert.equal(rezultat.greske[2], "Test6");
     assert.equal(rezultat.greske[3], "Test7");
   });
   it('Razliciti testovi, razlicita duzina TEST 1', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":5,\"passes\":2,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test4\",\"fullTitle\":\"Test4\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test5\",\"fullTitle\":\"Test5\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}", "{\"stats\":{\"suites\":2,\"tests\":3,\"passes\":2,\"pending\":0,\"failures\":1,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Test3\",\"fullTitle\":\"Test3\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Test1\",\"fullTitle\":\"Test1\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Test2\",\"fullTitle\":\"Test2\",\"file\":null,\"duration\":0,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "60%");
     assert.equal(rezultat.greske.length, 2);
   });
    
  });
});
